#!/bin/bash
# https://gist.github.com/zlbruce/883605a635df8d5964bab11ed75e46ad
echo "*** SVG 2 ICNS ***"
if [ $# -ne 1 ]; then
    echo "Usage:   svg2icns filename.svg"
    exit 100
fi
filename="$1"
name=${filename%.*}
ext=${filename##*.}
echo "processing: $name"
dest="$name".iconset
mkdir "$dest"

magick -background transparent -density 300 "$1" -resize 16x16 "$dest/icon_16x16.png"
magick -background transparent -density 300 "$1" -resize 32x32 "$dest/icon_16x16@2x.png"
cp "$dest/icon_16x16@2x.png" "$dest/icon_32x32.png"
magick -background transparent -density 300 "$1" -resize 64x64 "$dest/icon_32x32@2x.png"
magick -background transparent -density 300 "$1" -resize 128x128 "$dest/icon_128x128.png"
magick -background transparent -density 300 "$1" -resize 256x256 "$dest/icon_128x128@2x.png"
cp "$dest/icon_128x128@2x.png" "$dest/icon_256x256.png"
magick -background transparent -density 300 "$1" -resize 512x512 "$dest/icon_256x256@2x.png"
cp "$dest/icon_256x256@2x.png" "$dest/icon_512x512.png"
magick -background transparent -density 300 "$1" -resize 1024x1024 "$dest/icon_512x512@2x.png"

iconutil -c icns "$dest"
rm -R "$dest"
